'use strict';
const D=DokdoData, emblem=new Image();emblem.src='교표.jpg';
emblem.onload=()=>{for(const id of ['sani','nari']){avatar(id);let c=document.getElementById(id).getContext('2d');c.save();c.beginPath();c.arc(197,270,22,0,Math.PI*2);c.clip();c.drawImage(emblem,175,248,44,44);c.restore()}};
$('.mark').innerHTML='<img src="교표.jpg" alt="모덕초등학교 교표">';
$('#start').innerHTML='독도 탐험 입장하기 <span aria-hidden="true">➜</span>';
$('#guide').innerHTML='<button class="close" aria-label="닫기">×</button><span class="step">MODEOK EXPLORERS</span><h2>도구와 단서로 완성하는 독도 이야기</h2><p>6개 구역에서 탐험하고 아이템을 모아 나만의 전시관을 완성해 봐. 두 대원의 능력은 같고, 학년군에 따라 문제가 달라져.</p><p><b>WASD / 방향키</b> 이동 · <b>화면 드래그 / Q·R</b> 둘러보기<br><b>E</b> 조사 · <b>B</b> 가방 · <b>M</b> 지도 · <b>Esc</b> 닫기</p><p>아이템을 받으면 가방에서 <b>선택하기</b>를 눌러. 가까운 대상에 선택한 아이템을 사용하면 다음 단서가 열려!</p><p class="note">공간과 인물은 학습용 창작입니다. 실제 독도 지형이나 방문 동선을 재현한 지도가 아닙니다. 학습 자료의 출처는 게임 속 도움말에서 확인할 수 있어요.</p><button class="dialog-action" data-close>탐험 준비하기</button>';
$('#guide').querySelectorAll('.close,[data-close]').forEach(b=>b.onclick=()=>$('#guide').close());
$('footer span:last-child').textContent='독도 탐험대 · v1.0';
const game=document.createElement('section');game.className='game';game.hidden=true;game.setAttribute('aria-label','독도 탐험 게임');
game.innerHTML=`<canvas id="view" tabindex="0" aria-label="일인칭 탐험 공간. 방향키로 이동, Q와 R로 시점 회전, E로 가까운 대상 조사."></canvas>
<div class="hud"><img src="교표.jpg" alt="모덕초등학교 교표"><div><b>모덕초등학교 독도 탐험대</b><small id="player-info"></small></div></div>
<div class="toolbar"><button id="sound" aria-pressed="false">소리 꺼짐</button><button id="help-game">도움말</button><button id="exit-game">저장하고 나가기</button></div>
<div class="quest"><small id="chapter"></small><p id="quest-copy"></p><div class="progress-track"><span id="progress-fill"></span></div><span id="progress-count"></span></div>
<div id="heading">N</div><div class="crosshair" aria-hidden="true">+</div><div id="target"></div>
<button class="interact" hidden></button><div id="selected-tool"></div>
<div class="adventure-hotbar"><button id="bag-button">${itemIcon("bag")} <span>가방 B</span><b id="bag-count">0</b></button><button id="map-button">${itemIcon("map")} <span>지도 M</span></button><button id="journal-button">${itemIcon("notebook")} <span>수첩</span></button></div>
<div class="game-tip">WASD / 방향키 · 이동　드래그 / Q·R · 둘러보기<br>E · 조사　B · 가방　M · 지도<br><span id="save-status">진행 내용 자동 저장</span></div>
<div class="touch-pad" aria-label="이동 버튼"><button data-move="w" aria-label="앞으로">▲</button><button data-move="a" aria-label="왼쪽으로">◀</button><button data-move="s" aria-label="뒤로">▼</button><button data-move="d" aria-label="오른쪽으로">▶</button></div>
<div class="look-pad"><button data-move="q" aria-label="왼쪽 보기">↶</button><button data-move="r" aria-label="오른쪽 보기">↷</button></div>
<div class="toast" role="status"></div><dialog id="activity"></dialog></section>`;
document.body.append(game);
let view=$('#view');const gc=view.getContext('2d'),activity=$('#activity'),keys=new Set();
let state=D.fresh(),selected=null,active=false,px=0,pz=-7,yaw=0,pitch=-.06,last=0,frame=0,drag=null,nearest=null,sound=false,audioCtx=null,toastTimer=0,stationCubes=[],terrainFaces=[],collisions=[];
const slot=()=>`modeok-dokdo-escape-v1-${choice.character}-${choice.grade}`;
function save(){try{localStorage.setItem(slot(),JSON.stringify({...state,selected}));$('#save-status').textContent='✓ 이 기기에 자동 저장됨'}catch{$('#save-status').textContent='저장 공간을 사용할 수 없어요. 종료하면 진행이 사라질 수 있어요.'}}
function readSave(){try{let s=JSON.parse(localStorage.getItem(slot()));return D.valid(s)?s:null}catch{return null}}
function tone(ok=true){if(!sound)return;try{audioCtx ||= new (window.AudioContext||window.webkitAudioContext)();audioCtx.resume();let now=audioCtx.currentTime;[0,.13,.26].forEach((t,i)=>{let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=(ok?440:230)*[1,1.25,1.5][i];g.gain.setValueAtTime(.035,now+t);g.gain.exponentialRampToValueAtTime(.001,now+t+.2);o.connect(g);g.connect(audioCtx.destination);o.start(now+t);o.stop(now+t+.2)})}catch{}}
function toast(text){clearTimeout(toastTimer);$('.toast').textContent=text;toastTimer=setTimeout(()=>$('.toast').textContent='',3500)}
function modal(title,body,actions=[]){keys.clear();drag=null;activity.innerHTML=`<button class="close" aria-label="닫기">×</button><span class="step">${D.stages[state.stage].name} · 모덕초등학교</span><h2>${title}</h2><div class="activity-body">${body}</div><div class="actions"></div>`;activity.querySelector('.close').onclick=closeModal;for(const [label,fn,kind]of actions){let b=document.createElement('button');b.textContent=label;b.className=kind||'dialog-action';b.onclick=fn;activity.querySelector('.actions').append(b)}if(!activity.open)activity.showModal();activity.scrollTop=0}
function closeModal(){activity.close();keys.clear();view.focus()}
activity.addEventListener('cancel',()=>{keys.clear();if(!active){exitGame();return}setTimeout(()=>view.focus(),0)});
function refresh(){let s=D.stages[state.stage],count=s.nodes.filter(n=>state.done.includes(n.id)).length;$('#player-info').textContent=`${choice.character==='sani'?'산이':'나리'} · ${choice.grade}~${+choice.grade+1}학년 · ${s.name}`;$('#chapter').textContent=`CHAPTER ${String(state.stage+1).padStart(2,'0')} / 06 · ${s.name}`;$('#quest-copy').textContent=D.gate(state)?(state.stage===5?'전시가 완성됐어! 황금 깃발에서 수료증을 받아 줘.':'조사를 마쳤어! 황금 깃발로 가면 다음 구역이 열려.'):s.goal;$('#progress-count').textContent=`${count} / ${s.nodes.length} 조사 완료`;$('#progress-fill').style.width=`${count/s.nodes.length*100}%`;$('#bag-count').textContent=state.bag.length;$('#selected-tool').innerHTML=selected?`${itemIcon(selected)}<span>손에 든 아이템 · <b>${D.items[selected][1]}</b></span>`:'가방에서 사용할 아이템을 골라 줘';}
function enter(s){state=s;selected=state.bag.includes(s.selected)?s.selected:null;active=true;game.hidden=false;$('.shell').inert=true;document.body.classList.add('playing');resize();buildWorld();refresh();save();last=performance.now();cancelAnimationFrame(frame);frame=requestAnimationFrame(loop);modal(`${choice.character==='sani'?'산이':'나리'}, 탐험을 시작하자!`,`<p><b>${D.stages[state.stage].name}</b>에서 이야기가 이어져.</p><p>${D.stages[state.stage].goal}</p><div class="flow">걷기 <span>→</span> 조사하기 <span>→</span> 아이템 사용하기</div><p class="note">WASD나 방향키로 이동하고, 화면을 드래그하거나 Q·R로 둘러봐. 가까이 가면 조사 버튼이 나타나. 지도에서 목적지 안내도 받을 수 있어.</p>`,[['좋아, 출발!',closeModal]]);}
$('#start').onclick=()=>{sync();let s=readSave();if(!s){enter(D.fresh());return}game.hidden=false;$('.shell').inert=true;state=s;document.body.classList.add('playing');modal('탐험 기록을 찾았어!',`<p>${choice.character==='sani'?'산이':'나리'} · ${choice.grade}~${+choice.grade+1}학년</p><p><b>${D.stages[s.stage].name}</b> · ${s.done.length}개 활동 완료${s.finished?' · 수료 완료':''}</p><p>이전에 모은 아이템과 기록으로 이어갈 수 있어.</p>`,[['이어서 탐험하기',()=>{closeModal();enter(s)}],['새 탐험 시작',()=>modal('이 대원의 기록을 새로 시작할까?','<p>현재 캐릭터와 학년의 진행 기록이 새 탐험으로 바뀌어. 다른 캐릭터와 학년 기록은 남아 있어.</p>',[['새로 시작하기',()=>{closeModal();enter(D.fresh())}],['이어서 할래',()=>{closeModal();enter(s)},'secondary']]),'secondary']]);activity.querySelector('.close').onclick=exitGame};
function exitGame(){if(active)save();active=false;keys.clear();cancelAnimationFrame(frame);activity.close();game.hidden=true;$('.shell').inert=false;document.body.classList.remove('playing');$('#start').focus()}
$('#exit-game').onclick=exitGame;
$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=sound?'소리 켜짐':'소리 꺼짐';$('#sound').setAttribute('aria-pressed',sound);tone()};
$('#help-game').onclick=()=>modal('탐험 안내와 학습 자료',`<p>가까운 대상에 <b>E 또는 조사 버튼</b>을 사용해. 도구가 필요한 곳에서는 <b>가방 → 아이템 선택</b>이 먼저야.</p><p>WASD·방향키 이동 / 드래그·Q·R 둘러보기<br>B 가방 / M 지도 / Esc 창 닫기</p><p>진행은 캐릭터·학년별로 이 브라우저에 저장돼. 다른 기기나 브라우저로 자동 동기화되지는 않아.</p><h3>학습 내용 출처</h3><ul>${D.sources.map(([t,u])=>`<li><a href="${u}" target="_blank" rel="noopener">${t}</a></li>`).join('')}</ul><p class="note">공간·인물·장치는 가상의 학습용 구성입니다. 기록 카드는 원문을 쉽게 풀어 쓴 설명이며 실제 사료 이미지가 아닙니다. 역사 학습은 근거를 이해하고 서로 존중하는 태도로 진행합니다.</p>`,[['계속 탐험',closeModal]]);
function bag(){const target=nearest&&nearest.use&&!state.done.includes(nearest.id)?nearest:null;modal('① 가방에서 아이템 꺼내기',state.bag.length?`<p><b>아래 아이템 카드를 누르면 손에 들어.</b><br>가방이 닫힌 뒤 대상 가까이에서 <b>노란 사용 버튼</b>을 누르거나 <b>E</b>를 눌러 줘.</p>${target?`<div class="evidence">지금 앞에 있는 <b>${target.name}</b>에는<br><b>${D.items[target.use][1]}</b>을 사용하면 돼.</div>`:''}<div class="item-grid">${state.bag.map(id=>`<button class="item-card ${id===selected?'chosen':''}" data-item="${id}">${itemIcon(id)}<b>${D.items[id][1]}${target?.use===id?' · 지금 필요해!':''}</b><small>${D.items[id][2]}</small><em>${id===selected?'이미 손에 있어 · 다시 들기':'이 아이템 손에 들기'}</em></button>`).join('')}</div>`:'<p>아직 가방이 비어 있어. 먼저 탐험 안내원 가까이 가서 <b>조사하기</b>를 누르면 수첩을 받을 수 있어.</p>',[['사용 방법 보기',itemHow,'secondary'],['돌아가기',closeModal]]);activity.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{selected=b.dataset.item;save();refresh();closeModal();tone();toast(`${D.items[selected][1]}을 손에 들었어! 대상 가까이에서 노란 사용 버튼 또는 E를 눌러 줘.`)})}
$('#bag-button').onclick=bag;
function map(){let s=D.stages[state.stage];modal('탐험 지도',`<div class="chapter-list">${D.stages.map((x,i)=>`<span class="${i===state.stage?'current':''}">${i<state.stage?'✓':i+1} ${x.name}</span>`).join('')}</div><p class="note">게임 공간 안내도 · 실제 독도 지도와 다릅니다. 아래 목적지를 누르면 가까운 관찰 위치로 안내해요.</p><div class="node-map">${s.nodes.map(n=>`<button data-nav="${n.id}">${state.done.includes(n.id)?'✓':'◇'} ${n.name}<small>${state.done.includes(n.id)?'조사 완료':'조사하러 가기'}</small></button>`).join('')}<button data-nav="gate">⚑ ${state.stage===5?'수료 깃발':'다음 구역'}<small>${D.gate(state)?'이동 가능':'현재 구역 조사 후 열림'}</small></button></div>`,[['지도를 접기',closeModal]]);activity.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{let n=b.dataset.nav==='gate'?{x:0,z:11}:s.nodes.find(n=>n.id===b.dataset.nav);px=n.x;pz=n.z-1.6;yaw=0;pitch=0;closeModal();toast('목적지 앞에 도착했어. 직접 조사해 봐!')})}
$('#map-button').onclick=map;
$('#journal-button').onclick=()=>modal('나의 탐험 수첩',`<p>${state.notes.length}개 활동을 기록했어.</p>${state.bag.filter(id=>['land','bird','sea','archive','today','care'].includes(id)).map(id=>`<article class="record"><h3>${itemIcon(id)} ${D.items[id][1]}</h3><p>${D.items[id][2]}</p></article>`).join('')||'<p>관찰 기록을 모으면 여기에 쌓여.</p>'}<p class="note">지금까지 완료: ${state.notes.join(' · ')||'아직 없음'}</p>`,[['수첩 닫기',closeModal]]);
function finishNode(n){state=D.complete(state,n);if(n.grant?.length)selected=n.grant[n.grant.length-1];save();refresh();buildStations();tone();let reward=(n.grant||[]).map(id=>`<span>${itemIcon(id)}<b>${D.items[id][1]}</b></span>`).join('');modal('탐험 기록 완료!',`<p>${n.text||'모은 단서를 바르게 연결했어. 탐험 수첩에 기록했어!'}</p>${reward?`<div class="rewards">${reward}</div><p class="note">새 아이템을 가방에 넣고 선택했어. 다른 도구가 필요하면 가방에서 바꿔 줘.</p>`:''}<p>${D.gate(state)?'이 구역 조사가 끝났어! 황금 깃발로 가 보자.':'다른 조사 지점도 찾아보자.'}</p>`,[['계속 탐험',closeModal],['가방 확인',bag,'secondary']])}
function puzzle(n,index=0){const list=D.puzzles[n.puzzle][choice.grade],q=list[index];modal(n.name,`<div class="evidence"><small>사용 중인 단서</small><b class="evidence-item">${itemIcon(n.use)} ${D.items[n.use][1]}</b><p>${D.items[n.use][2]}</p></div><p class="question-number">${index+1} / ${list.length} 단서 연결</p><h3>${q.text}</h3><div class="answers">${q.options.map((o,i)=>`<button data-answer="${i}"><span>${i+1}</span>${o}</button>`).join('')}</div><p id="feedback" role="status"></p>`,[['가방 살펴보기',bag,'secondary']]);activity.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(+b.dataset.answer!==q.answer){$('#feedback').textContent='다시 살펴보자. '+q.explain;b.classList.add('incorrect');tone(false);return}activity.querySelectorAll('[data-answer]').forEach(x=>x.disabled=true);b.classList.add('correct');$('#feedback').textContent='맞아! '+q.explain;tone();let next=document.createElement('button');next.className='dialog-action';next.textContent=index+1<list.length?'다음 단서 연결하기':'기록 완성하기';next.onclick=()=>index+1<list.length?puzzle(n,index+1):finishNode(n);activity.querySelector('.actions').prepend(next);next.focus()})}
function interact(){if(!active||activity.open||!nearest)return;const n=nearest;if(n.id==='gate'){if(!D.gate(state)){toast('아직 조사하지 않은 지점이 있어. 지도를 확인해 줘.');return}if(state.stage===5){state=D.next(state);save();certificate();return}state=D.next(state);save();buildWorld();refresh();tone();modal(D.stages[state.stage].name,`<span class="chapter-subtitle">${D.stages[state.stage].subtitle}</span><p>${D.stages[state.stage].goal}</p>`,[['탐험 시작',closeModal]]);return}
let result=D.inspect(state,n,selected);if(result==='done'){modal(n.name,`<p>이미 조사한 곳이야.</p><p>${n.text||'단서를 연결해 기록을 완성했어.'}</p>`,[['돌아가기',closeModal]]);return}if(result==='requires'){modal('먼저 모아야 할 단서가 있어!',`<p>${(n.requires||[]).filter(id=>!state.bag.includes(id)).map(id=>D.items[id][1]).join(', ')}을 먼저 찾아 줘.</p>`,[['지도 확인',map],['돌아가기',closeModal,'secondary']]);return}if(result==='tool'){modal('알맞은 아이템을 사용해 줘',`<p><b>${n.name}</b>에는 <b>${D.items[n.use][1]}</b> 아이템이 필요해.</p><p>가방에서 아이템을 선택한 다음 다시 조사해 봐.</p>`,[['가방 열기',bag],['돌아가기',closeModal,'secondary']]);return}if(n.puzzle)puzzle(n);else modal(n.name,`<p>${n.text}</p>${n.use?`<p class="tool-use">${itemIcon(n.use)} ${D.items[n.use][1]} 사용</p>`:''}`,[[n.grant?.length?'아이템 받고 기록하기':'활동 완료하기',()=>finishNode(n)]])}
$('.interact').onclick=interact;
function certificate(){modal('독도 탐험을 완주했어!',`<div class="certificate" id="certificate"><img src="교표.jpg" alt="모덕초등학교 교표"><small>MODEOK EXPLORERS</small><h3>독도 탐험 완료증</h3><p class="recipient">${choice.character==='sani'?'산이':'나리'} 대원 · ${choice.grade}~${+choice.grade+1}학년</p><p>독도의 위치와 자연, 역사와 보전을 탐구하고<br>모은 단서로 독도 전시를 완성했습니다.</p><div class="seals"><span>▲ 지형</span><span>♧ 생태</span><span>▥ 역사</span><span>♥ 보전</span></div><b>모덕초등학교 독도 탐험대</b><p class="note">학습 게임 활동 완료 기념 · 공식 자격증이 아닙니다.</p></div>`,[['완료증 저장',downloadCertificate],['전시관 둘러보기',closeModal,'secondary']])}
function downloadCertificate(){const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const c=document.createElement('canvas');c.width=1200;c.height=850;const g=c.getContext('2d');g.fillStyle='#fffbed';g.fillRect(0,0,1200,850);g.strokeStyle='#46724b';g.lineWidth=10;g.strokeRect(35,35,1130,780);g.strokeStyle='#d2b365';g.lineWidth=3;g.strokeRect(52,52,1096,746);if(emblem.complete&&emblem.naturalWidth)g.drawImage(emblem,550,83,100,100);g.textAlign='center';g.fillStyle='#35553d';g.font='bold 54px Malgun Gothic';g.fillText('독도 탐험 완료증',600,275);g.font='bold 29px Malgun Gothic';g.fillText(`${choice.character==='sani'?'산이':'나리'} 대원 · ${choice.grade}~${+choice.grade+1}학년`,600,350);g.font='26px Malgun Gothic';g.fillText('독도의 위치와 자연, 역사와 보전을 탐구하고',600,440);g.fillText('모은 단서로 나만의 독도 전시를 완성했습니다.',600,487);g.font='bold 31px Malgun Gothic';g.fillText('모덕초등학교 독도 탐험대',600,620);g.font='18px Malgun Gothic';g.fillText('학습 게임 활동 완료 기념',600,684);const a=document.createElement('a');a.download=`독도탐험완료증_${choice.character}_${choice.grade}학년군.png`;a.href=c.toDataURL('image/png');a.click();toast('완료증 이미지 저장을 요청했어. 다운로드 폴더를 확인해 줘.')}
// World geometry. Static faces are built once; only visible cube sides are sent to the painter.
function boxFaces(x,y,z,w,h,d,c){return [
 {v:[[x,y,z],[x+w,y,z],[x+w,y+h,z],[x,y+h,z]],normal:[0,0,-1],c:shade(c,.86)},
 {v:[[x+w,y,z+d],[x,y,z+d],[x,y+h,z+d],[x+w,y+h,z+d]],normal:[0,0,1],c:shade(c,.78)},
 {v:[[x,y,z+d],[x,y,z],[x,y+h,z],[x,y+h,z+d]],normal:[-1,0,0],c:shade(c,.72)},
 {v:[[x+w,y,z],[x+w,y,z+d],[x+w,y+h,z+d],[x+w,y+h,z]],normal:[1,0,0],c:shade(c,.94)},
 {v:[[x,y+h,z],[x+w,y+h,z],[x+w,y+h,z+d],[x,y+h,z+d]],normal:[0,1,0],c:shade(c,1.1)}]}
function addBox(arr,x,y,z,w,h,d,c){arr.push(...boxFaces(x,y,z,w,h,d,c))}
function buildWorld(){px=0;pz=-7;yaw=0;pitch=-.05;terrainFaces=[];collisions=[];const base=D.stages[state.stage].color;
for(let x=-7;x<7;x++)for(let z=-10;z<14;z++){let c=state.stage===2||state.stage===4?((x+z)%2?'#90a578':'#849869'):((x+z)%2?'#c5b28a':'#bca67f');terrainFaces.push({v:[[x,0,z],[x+1,0,z],[x+1,0,z+1],[x,0,z+1]],normal:[0,1,0],c});}
for(let z=-10;z<14;z+=3)for(const x of [-7.1,7])addBox(terrainFaces,x,0,z,.15,1.15,.15,'#78694e');for(const x of [-7.1,7])addBox(terrainFaces,x,.9,-10,.12,.13,24,'#a08a63');addBox(terrainFaces,-7,.9,13.7,14,.12,.13,'#a08a63');
for(let a=0;a<2;a++)for(let x=-4;x<=4;x++)for(let z=-3;z<=3;z++){let t=1-x*x/21-z*z/13;if(t>0){let h=Math.ceil(t*(a?6:10));addBox(terrainFaces,x*1.8+(a?12:-11),-.6,z*1.8+31,1.8,h,1.8,(x+z)%2?'#85927e':'#708578');addBox(terrainFaces,x*1.8+(a?12:-11),h-.6,z*1.8+31,1.8,.15,1.8,'#a0b27e')}}
addBox(terrainFaces,12,5.5,31,.85,3,.85,'#f3eedb');addBox(terrainFaces,11.85,8.5,30.85,1.15,.23,1.15,'#bb715a');
// Clear, accessible central aisle. Decorative planters remain outside it.
for(const x of [-6.5,5.7])for(const z of [-5,8]){addBox(terrainFaces,x,0,z,.8,.6,.8,'#a99772');addBox(terrainFaces,x,.6,z,.8,.18,.8,base);addBox(terrainFaces,x+.2,.78,z+.2,.35,.7,.35,'#739451')}
buildStations();}
function buildStations(){stationCubes=[];collisions=[];for(const n of D.stages[state.stage].nodes){let x=n.x,z=n.z,done=state.done.includes(n.id),base=done?'#8fa580':D.stages[state.stage].color;collisions.push({x:x-.85,z:z-.45,w:1.7,d:1.2});
if(n.kind==='npc'){addBox(stationCubes,x-.35,0,z,.27,.65,.28,'#426e91');addBox(stationCubes,x+.08,0,z,.27,.65,.28,'#426e91');addBox(stationCubes,x-.4,.65,z-.1,.8,.85,.5,'#bcd780');addBox(stationCubes,x-.34,1.5,z-.1,.68,.6,.55,'#ebc3a1');addBox(stationCubes,x-.43,2.1,z-.15,.86,.15,.65,'#4d825e');addBox(stationCubes,x-.08,2.25,z,.2,.3,.25,'#72985e');}
else if(n.kind==='bird'){addBox(stationCubes,x-.7,0,z,1.4,.45,.9,base);addBox(stationCubes,x-.1,.45,z+.25,.35,.38,.35,'#fff9e2');addBox(stationCubes,x+.25,.6,z+.27,.2,.12,.12,'#eacb60');addBox(stationCubes,x-.5,.55,z+.24,.4,.09,.4,'#d5ded0');}
else if(n.kind==='litter'){addBox(stationCubes,x-.45,.03,z,.6,.06,.5,done?'#839969':'#e7ae7b');}
else if(n.kind==='chest'){addBox(stationCubes,x-.65,0,z,1.3,.8,.8,'#b68f56');addBox(stationCubes,x-.7,.8,z-.05,1.4,.17,.9,done?'#9bb67c':'#dac17a');addBox(stationCubes,x-.1,.4,z-.025,.2,.26,.05,'#f6df8b');}
else{addBox(stationCubes,x-.65,0,z,1.3,.9,.65,base);addBox(stationCubes,x-.85,.9,z-.08,1.7,.12,.83,'#d7c59e');if(n.kind==='sea'){addBox(stationCubes,x-.7,1.02,z,1.4,.9,.5,'#4c9b9a');for(let i=0;i<4;i++)addBox(stationCubes,x-.55+i*.3,1.05,z-.05,.12,.3+i%2*.3,.06,'#b6c475')}else{addBox(stationCubes,x-.65,1.03,z+.13,1.3,.6,.14,'#fff1ce');}}
}addBox(stationCubes,-.06,0,11,.12,3,.12,'#8b7753');addBox(stationCubes,.06,2.1,11,1.3,.85,.08,D.gate(state)?'#f4cd62':'#98a79a');}
function camera(p){let x=p[0]-px,z=p[2]-pz,y=p[1]-1.65,a=x*Math.cos(yaw)-z*Math.sin(yaw),b=x*Math.sin(yaw)+z*Math.cos(yaw);return[a,y*Math.cos(pitch)-b*Math.sin(pitch),y*Math.sin(pitch)+b*Math.cos(pitch)]}
function clip(v){let o=[];for(let i=0;i<v.length;i++){let a=v[i],b=v[(i+1)%v.length],ai=a[2]>.15,bi=b[2]>.15;if(ai)o.push(a);if(ai!==bi){let t=(.15-a[2])/(b[2]-a[2]);o.push(a.map((n,k)=>n+(b[k]-n)*t))}}return o}
function project(v){let f=Math.min(view.width,view.height)*.86;return [view.width/2+v[0]*f/v[2],view.height/2-v[1]*f/v[2]]}
function canWalk(x,z){return x>-6.6&&x<6.6&&z>-9.4&&z<13.2&&!collisions.some(c=>x>c.x-.23&&x<c.x+c.w+.23&&z>c.z-.23&&z<c.z+c.d+.23)}
function resize(){view.width=Math.round(innerWidth*Math.min(devicePixelRatio||1,1.3));view.height=Math.round(innerHeight*Math.min(devicePixelRatio||1,1.3))}
addEventListener('resize',resize);
function loop(t){if(!active)return;let dt=Math.min((t-last)/1000||0,.05);last=t;let moving=false;if(!activity.open){let fw=(keys.has('w')||keys.has('arrowup')?1:0)-(keys.has('s')||keys.has('arrowdown')?1:0),side=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),norm=Math.hypot(fw,side)||1;moving=!!(fw||side);yaw+=((keys.has('r')?1:0)-(keys.has('q')?1:0))*dt*1.4;let nx=px+(Math.sin(yaw)*fw+Math.cos(yaw)*side)/norm*dt*3.4,nz=pz+(Math.cos(yaw)*fw-Math.sin(yaw)*side)/norm*dt*3.4;if(canWalk(nx,pz))px=nx;if(canWalk(px,nz))pz=nz}
const w=view.width,h=view.height;let sky=gc.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#9acfdc');sky.addColorStop(1,'#e7edcf');gc.fillStyle=sky;gc.fillRect(0,0,w,h);let horizon=h/2+Math.tan(pitch)*Math.min(w,h)*.86;gc.fillStyle='#519daa';gc.fillRect(0,horizon,w,h);gc.fillStyle='#d3eee645';for(let i=0;i<12;i++)gc.fillRect((i*173+(t*.008)%150)%w,horizon+25+i*i*2,40+i*6,2);
const faces=[];for(const f of [...terrainFaces,...stationCubes]){const p=f.v[0];if(f.normal[0]*(px-p[0])+f.normal[1]*(1.65-p[1])+f.normal[2]*(pz-p[2])<=0)continue;let v=clip(f.v.map(camera));if(v.length<3)continue;let pts=v.map(project);if(pts.every(p=>p[0]<-50)||pts.every(p=>p[0]>w+50)||pts.every(p=>p[1]<-50)||pts.every(p=>p[1]>h+50))continue;faces.push({pts,c:f.c,d:v.reduce((n,p)=>n+p[2],0)/v.length})}faces.sort((a,b)=>b.d-a.d);for(const f of faces)poly(gc,f.pts,f.c);
const all=[...D.stages[state.stage].nodes,{id:'gate',name:state.stage===5?'探험 수료 깃발'.replace('探','탐'):'다음 구역으로',x:0,z:11}];nearest=null;let dist=3.4;
for(const n of all){let d=Math.hypot(n.x-px,n.z-pz),v=camera([n.x,2.8,n.z]);if(d<dist){dist=d;nearest=n}if(v[2]>.7){let p=project(v);if(p[0]>-80&&p[0]<w+80){let font=Math.max(12,Math.min(21,210/v[2]));gc.font=`bold ${font}px Malgun Gothic`;gc.textAlign='center';let text=(state.done.includes(n.id)?'✓ ':n.id==='gate'?'⚑ ':'◇ ')+n.name;let tw=gc.measureText(text).width;gc.fillStyle=n.id==='gate'&&D.gate(state)?'#ecd07bee':'#fffbeded';gc.fillRect(p[0]-tw/2-10,p[1]-font-7,tw+20,font+17);gc.fillStyle='#335b46';gc.fillText(text,p[0],p[1]);}}}
let bob=moving?Math.sin(t*.009)*h*.003:0;box(gc,w*.86,h*.81+bob,w*.095,h*.25,w*.025,choice.character==='sani'?'#bcd682':'#f4da82');box(gc,w*.845,h*.775+bob,w*.09,h*.085,w*.018,'#ecc19e');if(selected&&ItemPictures[selected]?.complete&&ItemPictures[selected].naturalWidth){const size=Math.min(w*.24,h*.27);gc.save();gc.translate(w*.86,h*.76+bob);gc.rotate(-.13);gc.drawImage(ItemPictures[selected],-size*.5,-size*.65,size,size);gc.restore()}
$('.interact').hidden=!nearest||activity.open;$('.interact').textContent=nearest?`E · ${nearest.id==='gate'?'깃발 확인':state.done.includes(nearest.id)?'기록 다시 보기':nearest.use?(selected===nearest.use?D.items[nearest.use][1]+' 사용하기':D.items[nearest.use][1]+' 꺼내는 방법'):'조사하기'}`:'';$('#target').textContent=nearest&&!activity.open?nearest.name:'';$('#heading').textContent=`${['북 N','동 E','남 S','서 W'][((Math.round(yaw/(Math.PI/2))%4)+4)%4]} · ${D.stages[state.stage].name}`;frame=requestAnimationFrame(loop)}
addEventListener('keydown',e=>{if(!active)return;let k=e.key.toLowerCase();if(activity.open)return;if(['w','a','s','d','q','r','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){e.preventDefault();keys.add(k)}if(e.repeat)return;if(k==='e')interact();if(k==='b')bag();if(k==='m')map()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{keys.clear();drag=null});document.addEventListener('visibilitychange',()=>{keys.clear();drag=null});
view.onpointerdown=e=>{if(activity.open)return;drag=[e.clientX,e.clientY];view.setPointerCapture(e.pointerId)};view.onpointermove=e=>{if(!drag)return;yaw+=(e.clientX-drag[0])*.004;pitch=Math.max(-.7,Math.min(.7,pitch-(e.clientY-drag[1])*.003));drag=[e.clientX,e.clientY]};for(const evt of ['pointerup','pointercancel','lostpointercapture'])view.addEventListener(evt,()=>drag=null);
document.querySelectorAll('[data-move]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();keys.add(b.dataset.move);b.setPointerCapture(e.pointerId)};for(const evt of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(evt,()=>keys.delete(b.dataset.move))});
function itemHow(){modal('아이템은 이렇게 사용해!',`<ol class="use-steps"><li><b>가방 열기</b><p>화면 아래 <strong>가방</strong> 버튼을 눌러. 키보드는 <strong>B</strong>야.</p></li><li><b>아이템을 손에 들기</b><p>사용할 <strong>아이템 카드</strong>를 눌러. 가방이 닫히고 화면 아래에 선택한 이름이 보여.</p></li><li><b>사용할 곳으로 가기</b><p>대상 가까이 걸어가면 <strong>노란 사용 버튼</strong>이 나타나. 길을 모르겠으면 <strong>지도</strong>에서 목적지를 골라 줘.</p></li><li><b>노란 사용 버튼 누르기</b><p>버튼을 누르거나 키보드 <strong>E</strong>를 누르면 돼. 화면의 대상에 아이템을 끌어다 놓을 필요는 없어.</p></li></ol><div class="evidence"><b>예시 · 바위섬 관찰하기</b><p>가방 → 쌍안경 카드 → 동도·서도 관찰 지점 → <strong>쌍안경 사용하기</strong></p></div><p class="note">새로 받은 아이템은 자동으로 손에 들어. 다음 장소에서 다른 도구가 필요하면 가방에서 바꿔 줘. 사용한 도구와 기록은 가방에 계속 남아 있어.</p>`,[['가방 열어보기',bag],['이제 해볼게!',closeModal,'secondary']]);}
const originalHelp=$('#help-game').onclick;$('#help-game').textContent='아이템 사용법';$('#help-game').onclick=()=>{itemHow();const b=document.createElement('button');b.textContent='전체 도움말·출처';b.className='secondary';b.onclick=originalHelp;activity.querySelector('.actions').append(b)};
