document.title='독도 수호대 · 여섯 개의 비밀 문';
$('.eyebrow').textContent='모덕초등학교 · 단서로 여는 방탈출 탐험';$('h1').innerHTML='독도<br><span>수호대</span>';
$('.intro>p').innerHTML='잠긴 여섯 개의 방, 흩어진 독도의 단서.<br>산이·나리와 비밀 문을 열고 독도를 지켜 줘!';$('.mission p').innerHTML='<b>MISSION 01 · 탐사 준비실 탈출</b><br>찾고 → 관찰하고 → 연결하면 문이 열려!';
$('#start').innerHTML='독도 수호 임무 시작 <span aria-hidden="true">→</span>';$('.hud b').textContent='모덕초등학교 독도 수호대';
$('#guide h2').textContent='여섯 개의 비밀 문을 열고 독도를 지켜 줘';$('#guide>p').textContent='독도 수호대원이 되어 여섯 방의 단서를 찾아봐. 사진·기록을 관찰하고 알맞은 아이템을 사용한 뒤 출구에서 단서를 조합하면 다음 방이 열려. 마지막 통신실에서는 독도의 자연을 아끼고 사실을 바르게 알리는 보호 계획을 완성해. 시간제한과 생명 차감은 없어.';
const missionRefresh=refresh;refresh=function(){missionRefresh();const room=EscapeRooms[state.stage];$('#chapter').textContent=`ROOM ${state.stage+1} / 6 · ${room.name}`;$('#quest-copy').textContent=D.gate(state)?`${room.lock} 준비 완료! 출구로 가서 단서를 연결해 줘.`:room.goal;$('#progress-count').textContent+=D.gate(state)?' · 출구 장치 작동 가능':' · 출구 잠김';};
const missionModal=modal;modal=function(title,body,actions){body=body.replaceAll('황금 깃발','출구 잠금장치').replaceAll('나만의 전시','독도 보호 계획').replaceAll('전시가 완성','수호 메시지가 완성');missionModal(title,body,actions)};
const doorInteract=interact;
interact=function(){if(!active||activity.open||!nearest)return;if(nearest.id!=='gate'){doorInteract();return}if(!D.gate(state)){const missing=D.stages[state.stage].nodes.filter(n=>!state.done.includes(n.id));modal('아직 봉인된 문이야',`<div class="door-symbol">🔒</div><p>이 방에 남은 단서 ${missing.length}개를 먼저 해결해야 해.</p><ul>${missing.map(n=>`<li>${n.name}</li>`).join('')}</ul><p>장치를 파괴하는 대신, 관찰한 사실과 도구로 잠금을 풀어 보자.</p>`,[['단서 지도 보기',map],['돌아가기',closeModal,'secondary']]);return}openEscapeLock();};$('.interact').onclick=interact;
function openEscapeLock(){const index=state.stage,room=EscapeRooms[index];let picks=[];
const visual=room.visual==='islands'?'<p class="note">두 실제 사진을 비교해 줘. 사진은 각 카드에 있어.</p>':room.visual==='final'?photoFigure('panorama',false):learningDiagram(room.visual);
modal(room.lock,`<span class="escape-tag">${index===5?'FINAL SIGNAL':'DOOR '+(index+1)} · 단서 조합</span><h3>${room.prompt}</h3>${visual}<div class="lock-slots">${room.answer.map((_,i)=>`<span data-lock-slot="${i}">${i+1}번째 단서</span>`).join('')}</div><div class="lock-cards">${room.cards.map(([text,id],i)=>`<button data-lock-card="${i}">${room.visual==='islands'?`<img src="assets/photos/${DokdoPhotos[id].file}" alt="${text}: 실제 섬 사진">`:itemIcon(id)}<strong>${text}</strong></button>`).join('')}</div>${room.visual==='islands'?photoCredit('east')+photoCredit('west'):''}<p id="lock-feedback" role="status">카드를 순서대로 누른 뒤 잠금을 확인해 줘.</p><p class="note">${choice.grade==='1'?'천천히 그림과 이름을 연결해 봐. 시간제한은 없어.':choice.grade==='3'?'단서를 고른 까닭도 생각해 봐.': '사진·기록에서 확인한 사실을 근거로 연결해 봐.'}</p>`,[['잠금 확인',verify],['다시 조합',reset,'secondary']]);
function reset(){picks=[];activity.querySelectorAll('[data-lock-slot]').forEach((el,i)=>{el.textContent=`${i+1}번째 단서`;el.classList.remove('filled')});activity.querySelectorAll('[data-lock-card]').forEach(b=>b.disabled=false);$('#lock-feedback').textContent='단서를 다시 연결해 보자.';}
activity.querySelectorAll('[data-lock-card]').forEach(b=>b.onclick=()=>{if(picks.length===room.answer.length)return;const i=+b.dataset.lockCard,slot=activity.querySelector(`[data-lock-slot="${picks.length}"]`);picks.push(i);slot.textContent=room.cards[i][0];slot.classList.add('filled');b.disabled=true});
function verify(){if(picks.length!==room.answer.length){$('#lock-feedback').textContent='빈칸을 모두 채워 줘.';return}if(!picks.every((v,i)=>v===room.answer[i])){$('#lock-feedback').textContent='아직 잠겨 있어. 위의 사진·그림과 문제에 적힌 순서를 다시 살펴봐. 다시 조합을 누르면 바꿀 수 있어.';tone(false);return}state.seals=[...new Set([...(state.seals||[]),index])];save();buildStations();tone();modal(index===5?'독도 수호 메시지 완성!':'철컥! 비밀 문이 열렸어',`<div class="door-symbol">${index===5?'🛡️':'🔓'}</div><p>${index===5?'우리는 독도의 모습을 관찰하고, 역사 기록을 확인하고, 생물의 삶터를 보호하는 방법을 찾았어.':room.name+'의 단서를 연결해 잠금장치를 해제했어.'}</p><p>${index===5?'네가 모은 증거로 독도를 지키는 계획이 완성됐어!':'다음 방: '+EscapeRooms[index+1].name}</p>`,[[index===5?'수호 임무 완료':'열린 문으로 이동',()=>{state=D.next(state);save();if(index===5){certificate();return}buildWorld();refresh();closeModal();toast(EscapeRooms[state.stage].goal)}]]);}}
const expeditionCertificate=certificate;certificate=function(){expeditionCertificate();activity.querySelector('h2').textContent='독도 수호 임무를 완수했어!';activity.querySelector('.certificate h3').textContent='독도 수호대 완료증';const ps=activity.querySelectorAll('.certificate p');ps[1].innerHTML='여섯 방의 단서를 연결하고<br>독도를 지키는 보호 계획을 완성했습니다.';activity.querySelectorAll('button').forEach(b=>{if(b.textContent==='전시관 둘러보기')b.textContent='수호 통신실 둘러보기'});};
const originalItemHow=itemHow;itemHow=function(){originalItemHow();activity.querySelector('.activity-body').insertAdjacentHTML('afterbegin','<div class="escape-intro"><b>독도 수호대의 약속</b><p>독도를 지킨다는 것은 자연을 아끼고, 역사적 근거를 확인하고, 사실을 바르게 알리는 일이야. 각 방의 단서를 해결한 뒤 출구 장치에서 마지막 조합을 완성하자.</p></div>')};$('#help-game').onclick=itemHow;
downloadCertificate=function(){const c=document.createElement('canvas');c.width=1200;c.height=850;const g=c.getContext('2d');g.fillStyle='#fffbed';g.fillRect(0,0,1200,850);g.strokeStyle='#386354';g.lineWidth=10;g.strokeRect(35,35,1130,780);g.strokeStyle='#d7b368';g.lineWidth=3;g.strokeRect(52,52,1096,746);if(emblem.complete&&emblem.naturalWidth)g.drawImage(emblem,550,85,100,100);g.textAlign='center';g.fillStyle='#355b49';g.font='bold 54px Malgun Gothic';g.fillText('독도 수호대 완료증',600,280);g.font='bold 29px Malgun Gothic';g.fillText(`${choice.character==='sani'?'산이':'나리'} 대원 · ${choice.grade}~${+choice.grade+1}학년`,600,355);g.font='26px Malgun Gothic';g.fillText('여섯 방의 단서를 연결하고',600,445);g.fillText('독도를 지키는 보호 계획을 완성했습니다.',600,490);g.font='bold 31px Malgun Gothic';g.fillText('모덕초등학교 독도 수호대',600,625);g.font='18px Malgun Gothic';g.fillText('학습 게임 활동 완료 기념',600,685);const a=document.createElement('a');a.download=`독도수호대완료증_${choice.character}_${choice.grade}학년군.png`;a.href=c.toDataURL('image/png');a.click();};
