// First-person entry scene: CPU perspective rendering, no network dependency.
const emblem=new Image();emblem.src='교표.jpg';emblem.onload=()=>{avatar('sani');avatar('nari');for(const id of ['sani','nari']){let c=document.getElementById(id).getContext('2d');c.save();c.beginPath();c.arc(197,270,22,0,Math.PI*2);c.clip();c.drawImage(emblem,175,248,44,44);c.restore()}};
document.querySelector('.mark').innerHTML='<img src="교표.jpg" alt="모덕초등학교 교표">';
document.querySelector('#start').innerHTML='독도 탐험 입장하기 <span aria-hidden="true">➜</span>';
document.querySelector('#guide .note').textContent='현재는 대원 선택과 일인칭 탐험 기지 입장, 탐험 수첩 받기까지 체험할 수 있어요. 독도를 모티브로 만든 가상 학습 공간입니다.';
const game=document.createElement('section');game.className='game';game.hidden=true;game.setAttribute('aria-label','독도 일인칭 탐험 기지');game.innerHTML=`<canvas id="view" tabindex="0" aria-label="일인칭 탐험 공간. WASD 또는 방향키로 이동하고 화면을 드래그해 둘러보세요."></canvas><div class="hud"><img src="교표.jpg" alt="모덕초등학교 교표"><div><b>모덕초등학교 독도 탐험대</b><small id="player-info"></small></div></div><button class="exit-game">나가기</button><div class="quest"><small>MISSION 01 · 탐험의 시작</small><p id="quest-copy">앞에 있는 탐험 기지 안내판에 다가가<br><b>첫 번째 탐험 수첩</b>을 받아 보자.</p></div><div class="crosshair" aria-hidden="true">+</div><div class="inventory"><div><span>▧</span>지도</div><div><span>▣</span>카메라</div><div id="notebook"><span>?</span>빈칸</div></div><button class="interact" hidden>E · 탐험 수첩 받기</button><div class="game-tip">W A S D / 방향키 · 이동<br>화면 드래그 · 둘러보기　E · 상호작용<br>가상 탐험 기지 · 제작 모덕초등학교</div><div class="touch-pad" aria-label="이동 버튼"><button data-move="w" aria-label="앞으로">▲</button><button data-move="a" aria-label="왼쪽으로">◀</button><button data-move="s" aria-label="뒤로">▼</button><button data-move="d" aria-label="오른쪽으로">▶</button></div><div class="toast" role="status"></div><div class="welcome"><div class="welcome-card"><img src="교표.jpg" alt="모덕초등학교 교표"><span class="step">WELCOME TO DOKDO</span><h2 id="greeting"></h2><p>여기는 <b>모덕초등학교 독도 탐험 기지</b>야.<br>직접 걸어가며 주변을 둘러보고,<br>안내판에서 탐험 수첩을 받아 보자!</p><p class="note">마우스로 화면을 누른 채 움직이면 주변을 볼 수 있어. 키보드나 화면의 화살표로 이동해 봐.</p><button id="walk">좋아, 탐험 시작!</button></div></div>`;document.body.append(game);
const view=$('#view'),gc=view.getContext('2d'),keys=new Set();let active=false,welcoming=false,collected=false,frame=0,last=0,px=0,pz=-9,yaw=0,pitch=0,drag=null;const cubes=[];
function cube(x,y,z,w,h,d,c){cubes.push({x,y,z,w,h,d,c})}
// A bounded landing deck with railings, grass terraces, distant rocky islands and a station.
for(let x=-7;x<7;x++)for(let z=-13;z<8;z++)cube(x,-.25,z,1,.25,1,(x+z)%2?'#c3af83':'#b9a17b');
for(let z=-13;z<8;z+=2){for(const x of [-7.2,7.1])cube(x,0,z,.16,1.2,.16,'#76684d')}
cube(-7.2,.9,-13,.12,.12,21,'#967f59');cube(7.1,.9,-13,.12,.12,21,'#967f59');
for(let x=-7;x<7;x+=2)cube(x,0,7.2,.16,1.2,.16,'#76684d');cube(-7,.9,7.2,14,.12,.12,'#967f59');
for(let a=0;a<2;a++)for(let x=-4;x<=4;x++)for(let z=-3;z<=3;z++){const t=1-x*x/21-z*z/13;if(t>0){let h=Math.ceil(t*(a?7:10));cube(x*1.8+(a?11:-10),-.6,z*1.8+27,1.8,h,1.8,(x+z)%2?'#83917e':'#697f75');cube(x*1.8+(a?11:-10),h-.6,z*1.8+27,1.8,.2,1.8,'#9cad73')}}
cube(-1.6,0,2,.18,2.7,.18,'#735b3b');cube(1.5,0,2,.18,2.7,.18,'#735b3b');cube(-1.8,1.3,2,3.6,1.65,.2,'#eee7cc');cube(-1.95,2.98,1.8,3.9,.17,.65,'#3c7456');
cube(-5,0,3,1.9,.8,1.5,'#54835d');cube(-5,.8,3,1.9,.12,1.5,'#b4cb83');cube(4,0,3,1.7,.7,1.5,'#b18b50');cube(4,.7,3,1.7,.12,1.5,'#dbc17c');
cube(11,6.6,27,.8,2.8,.8,'#efe9d5');cube(10.85,9.4,26.85,1.1,.25,1.1,'#b6674d');
function camera(p){let x=p[0]-px,z=p[2]-pz,y=p[1]-1.65;let a=x*Math.cos(yaw)-z*Math.sin(yaw),b=x*Math.sin(yaw)+z*Math.cos(yaw);return[a,y*Math.cos(pitch)-b*Math.sin(pitch),y*Math.sin(pitch)+b*Math.cos(pitch)]}
function clip(v){let o=[];for(let i=0;i<v.length;i++){let a=v[i],b=v[(i+1)%v.length],ai=a[2]>.12,bi=b[2]>.12;if(ai)o.push(a);if(ai!==bi){let t=(.12-a[2])/(b[2]-a[2]);o.push(a.map((n,k)=>n+(b[k]-n)*t))}}return o}
function screen(v,w,h){const f=Math.min(w,h)*.86;return[w/2+v[0]*f/v[2],h/2-v[1]*f/v[2]]}
function scene(t){if(!active)return;let dt=Math.min((t-last)/1000||0,.045);last=t;if(!welcoming){let forward=(keys.has('w')||keys.has('arrowup')?1:0)-(keys.has('s')||keys.has('arrowdown')?1:0),side=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),norm=Math.hypot(forward,side)||1;let nx=px+(Math.sin(yaw)*forward+Math.cos(yaw)*side)/norm*dt*3.1,nz=pz+(Math.cos(yaw)*forward-Math.sin(yaw)*side)/norm*dt*3.1;nx=Math.max(-6.6,Math.min(6.6,nx));nz=Math.max(-12.5,Math.min(6.5,nz));if(!(nx>-2.15&&nx<2.15&&nz>1.5&&nz<2.8)&&!(nx<-2.7&&nx>-5.5&&nz>2.5&&nz<5)&&!(nx>3.5&&nz>2.5&&nz<5)){px=nx;pz=nz}}
const w=view.width,h=view.height;gc.fillStyle='#b9dfe2';gc.fillRect(0,0,w,h);let horizon=h/2+Math.tan(pitch)*Math.min(w,h)*.86;gc.fillStyle='#4a9eac';gc.fillRect(0,horizon,w,h);const faces=[];
for(const b of cubes){let {x,y,z,w:ww,h:hh,d,c}=b;let vs=[[x,y,z],[x+ww,y,z],[x+ww,y+hh,z],[x,y+hh,z],[x,y,z+d],[x+ww,y,z+d],[x+ww,y+hh,z+d],[x,y+hh,z+d]].map(camera);[[[0,1,2,3],.9],[[5,4,7,6],.7],[[4,0,3,7],.78],[[1,5,6,2],.82],[[3,2,6,7],1.1]].forEach(([ids,s])=>{let v=clip(ids.map(i=>vs[i]));if(v.length>2)faces.push({v,c:shade(c,s),d:v.reduce((n,p)=>n+p[2],0)/v.length})})}faces.sort((a,b)=>b.d-a.d);for(const face of faces)poly(gc,face.v.map(v=>screen(v,w,h)),face.c);
// Billboard lettering is projected to the actual station position.
let sign=camera([0,2.15,1.97]);if(sign[2]>.5&&Math.cos(yaw)>.2){let s=screen(sign,w,h),sz=Math.min(42,Math.min(w,h)*.86/sign[2]*.22);gc.textAlign='center';gc.fillStyle='#295940';gc.font=`bold ${sz}px Malgun Gothic`;gc.fillText('모덕초등학교',s[0],s[1]-sz*.7);gc.font=`bold ${sz*.73}px Malgun Gothic`;gc.fillText('독도 탐험 기지',s[0],s[1]+sz*.5);if(emblem.complete&&emblem.naturalWidth)gc.drawImage(emblem,s[0]-sz*.5,s[1]+sz*.9,sz,sz)}
// Selected character's first-person sleeve and hand.
box(gc,w*.83,h*.80,w*.1,h*.24,w*.035,choice.character==='sani'?'#bdd885':'#f5db83');box(gc,w*.82,h*.77,w*.09,h*.075,w*.025,'#f0c5a0');
const near=Math.hypot(px,pz-1.2)<3.1;$('.interact').hidden=!near||collected||welcoming;frame=requestAnimationFrame(scene)}
function resizeGame(){view.width=Math.round(innerWidth*Math.min(devicePixelRatio||1,1.3));view.height=Math.round(innerHeight*Math.min(devicePixelRatio||1,1.3))}addEventListener('resize',resizeGame);
$('#start').onclick=()=>{sync();px=0;pz=-9;yaw=0;pitch=-.035;collected=false;$('#notebook').innerHTML='<span>?</span>빈칸';$('#quest-copy').innerHTML='앞에 있는 탐험 기지 안내판에 다가가<br><b>첫 번째 탐험 수첩</b>을 받아 보자.';$('#player-info').textContent=`${choice.character==='sani'?'산이':'나리'} · ${choice.grade}~${+choice.grade+1}학년 · 일인칭 탐험`;$('#greeting').textContent=`${choice.character==='sani'?'산이':'나리'}, 독도에 온 걸 환영해!`;document.querySelector('.shell').inert=true;document.querySelector('.toast').textContent='';drag=null;keys.clear();game.hidden=false;document.body.classList.add('playing');$('.welcome').hidden=false;welcoming=true;active=true;resizeGame();cancelAnimationFrame(frame);last=performance.now();frame=requestAnimationFrame(scene);$('#walk').focus()};
$('#walk').onclick=()=>{welcoming=false;$('.welcome').hidden=true;view.focus()};$('.exit-game').onclick=()=>{active=false;keys.clear();cancelAnimationFrame(frame);game.hidden=true;document.querySelector('.shell').inert=false;document.body.classList.remove('playing');$('#start').focus()};
function interact(){if(!active||welcoming||collected||Math.hypot(px,pz-1.2)>=3.1)return;collected=true;$('#notebook').innerHTML='<span>▤</span>탐험 수첩';$('#quest-copy').innerHTML='<b>탐험 수첩 받기 완료!</b><br>독도 탐험을 위한 준비를 마쳤어.';$('.toast').textContent='탐험 수첩을 얻었어! 다음 탐험에서는 이 수첩에 단서를 기록하게 될 거야. 이번 입장 체험은 여기까지야.';setTimeout(()=>$('.toast').textContent='',6500)}$('.interact').onclick=interact;
addEventListener('keydown',e=>{if(!active)return;let k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){e.preventDefault();keys.add(k)}if(k==='e')interact();if(k==='escape')keys.clear()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>keys.clear());
view.addEventListener('pointerdown',e=>{if(welcoming)return;drag=[e.clientX,e.clientY];view.setPointerCapture(e.pointerId)});view.addEventListener('pointermove',e=>{if(!drag)return;yaw+=(e.clientX-drag[0])*.004;pitch=Math.max(-.65,Math.min(.65,pitch-(e.clientY-drag[1])*.003));drag=[e.clientX,e.clientY]});for(const evt of ['pointerup','pointercancel','lostpointercapture'])view.addEventListener(evt,()=>drag=null);
document.querySelectorAll('[data-move]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();keys.add(b.dataset.move);b.setPointerCapture(e.pointerId)};for(const evt of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(evt,()=>keys.delete(b.dataset.move))});
